### ISSUE TITLE
Test stableness tracker

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/benchmark#1409]
# CPU
CPU eval test: https://github.com/pytorch/benchmark/actions/runs/4145537778

# GPU

- [ ] Yolov3 train: https://github.com/pytorch/benchmark/actions/runs/4145521493
- [ ] Yolov3 eval: https://github.com/pytorch/benchmark/actions/runs/4146281655
- [ ] pytorch_CycleGAN_and_pix2pix train: https://github.com/pytorch/benchmark/actions/runs/4147131894
- [ ] timm_vision_transformer train: https://github.com/pytorch/benchmark/actions/runs/4147202172
- [ ] DALLE2_pytorch eval: https://github.com/pytorch/benchmark/actions/runs/4147979273

**Comment by xuzhao9** [comment]
# CPU
CPU eval test: https://github.com/pytorch/benchmark/actions/runs/4145537778

**Comment by xuzhao9** [comment]
Run test workflow: https://github.com/pytorch/benchmark/actions/runs/4570186138
