### ISSUE TITLE
Fix V2 bisection backlog

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/benchmark#2041]
```[tasklist]
### Tasks
- [x] bisection-gh6707630439 [link](https://github.com/pytorch/benchmark/actions/runs/6710053921) [rerun](https://github.com/pytorch/benchmark/actions/runs/6884762526)
- [x] bisection-gh6407125260 [link](https://github.com/pytorch/benchmark/actions/runs/6409249711) [rerun](https://github.com/pytorch/benchmark/actions/runs/6886585482)
- [x] bisection-gh6891812881 [link](https://github.com/pytorch/benchmark/actions/runs/6898271942)
- [x] bisection-gh6904963254 [link](https://github.com/pytorch/benchmark/actions/runs/6907107994/job/18793577498)
- [ ] bisection-gh6470437914: 2023-10-09(97287ff) to 2023-10-10(c5b2551): [link](https://github.com/pytorch/benchmark/actions/runs/6914288405)
- [ ] 2023-06-22 to 2023-09-08
```

**Comment by xuzhao9** [comment]
The error is because CUDA 11.8 is required to build Kineto while V2 was still using 11.7 as default. Upgraded to 11.8.

**Comment by xuzhao9** [comment]
```
{
  "start": "92fea5ae3f5307b8ebf5e9cb123d971237f8bf03",
  "end": "468a73f0e3527c52495c864c7d48dc26684f6c0b",
  "threshold": 7,
  "timeout": 120,
  "torchbench_branch": "v2.0",
  "result": []
}
```
